version: 2

jobs:
  build:
    branches:
      only:
        - master
        - beta
    docker:
      - image: 'circleci/node:12'
    steps:
      - checkout
      - restore_cache:
          name: Restore NPM Package Cache
          keys:
            - npm-packages-{{ checksum "package-lock.json" }}

      - run:
          name: Install Dependencies
          command: npm ci

      - save_cache:
          name: Save Npm Package Cache
          key: npm-packages-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/npm

      - run:
          name: Test
          command: npm run lint
      - run:
          name: Build
          command: npm run build:lib
      - run:
          name: release
          command: npm run semantic-release
